title=Список книг
library=Учебная библиотека
reader=Читатель
unnamed=без имени
name=Имя читателя
language=Язык
filter=Какие книги показать
all=Все книги
read=Прочитанные
unread=Непрочитанные
submit=Показать книги
author=Автор
book.title=Название книги
book.read=Прочитал
yes=Да
no=Нет
count=Найдено книг
method=Метод запроса
book.1.author=Михаил Булгаков
book.1.title=Мастер и Маргарита
book.2.author=Виктор Пелевин
book.2.title=Чапаев и Пустота
book.3.author=Лев Толстой
book.3.title=Война и мир
book.4.author=Фёдор Достоевский
book.4.title=Идиот